vizClusterPhenotype=function(Build,markerUse,outDir){
	#purpose: Visualize the phenotype for each cluster generated by VoPo
		#If there were 50 iterations run with 30 clusters each, there will be 1500 clusters (points)
		#We will generate a plot of clusters colored by each marker of interest

	#inputs:
		#Build: The object returned by VoPo clustering runRepMetaclust.R
		#markerUse: This is a vector of indices corresponding to the markers you want to use to project cells into 2D
			#for example: if you to project clusters based on expression of CD3, CD16, CD56 which correspond to channels 2,3, and 5 in FCS files markerUse=c(2,3,5)
		#Y: A matrix of two dimensions representing 
		#outDir: The path to where you want plots saved
			#for example: '~/MyPhenotypePlots'


	#outputs:
		#This function returns the coordinates of the Layout used to project clusters into 2 dimensions
		#This function will save the plots to outDir. There should be as many plots as the length of your ToUse argument

library('ggplot2')
library('reshape2')
library('viridis')

clFeat=Build[[4]][,markerUse]
pc=prcomp(scale(clFeat))
Y=pc$x[,1:2]

for(i in 1:ncol(clFeat)){
    NetDF=data.frame(Y[,1],Y[,2],clFeat[,i])
    names(NetDF)=c('PC1','PC2','Marker')
    FName=paste(outDir,'/',colnames(clFeat)[i],'.jpg',sep='')
    p=ggplot(NetDF, aes(PC1,PC2,color=Marker))+geom_point()+ scale_color_viridis()+ theme_bw()+ theme(text = element_text(size=20))+ggtitle(colnames(clFeat)[i])+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"))
    ggsave(FName,p,width=7,height=7)
    }

Y
}